// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0cyiUoCdjrq24nr0-AjznBV79DEHwLt4',
    appId: '1:832178833492:web:eeeeb24a37801f550cc5c1',
    messagingSenderId: '832178833492',
    projectId: 'chatup-98428',
    authDomain: 'chatup-98428.firebaseapp.com',
    databaseURL: 'https://chatup-98428-default-rtdb.firebaseio.com',
    storageBucket: 'chatup-98428.appspot.com',
    measurementId: 'G-JY6SWK2FHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWqc_Qg-iMLbp6jDwCiq8rZpcIeZOgeKU',
    appId: '1:832178833492:android:a1ef36dfd4ebc3de0cc5c1',
    messagingSenderId: '832178833492',
    projectId: 'chatup-98428',
    databaseURL: 'https://chatup-98428-default-rtdb.firebaseio.com',
    storageBucket: 'chatup-98428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6s-wcLJZuhhCfDJVcPU83eIHEoItNQ2Y',
    appId: '1:832178833492:ios:ca882f01316b33d60cc5c1',
    messagingSenderId: '832178833492',
    projectId: 'chatup-98428',
    databaseURL: 'https://chatup-98428-default-rtdb.firebaseio.com',
    storageBucket: 'chatup-98428.appspot.com',
    iosClientId: '832178833492-1nhptvoeghnsb7uvk33k7k1903t43h6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6s-wcLJZuhhCfDJVcPU83eIHEoItNQ2Y',
    appId: '1:832178833492:ios:90e68353ab4200840cc5c1',
    messagingSenderId: '832178833492',
    projectId: 'chatup-98428',
    databaseURL: 'https://chatup-98428-default-rtdb.firebaseio.com',
    storageBucket: 'chatup-98428.appspot.com',
    iosClientId: '832178833492-t64imt7265sefvfh2r78rnlh3gelf0jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
